# Generated by Django 5.2.7 on 2025-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('host', models.CharField(max_length=255)),
                ('path_prefix', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(default=500)),
                ('enable', models.BooleanField(default=True)),
                ('response_body', models.TextField(verbose_name='{"error":"mocked error"}')),
                ('content_type', models.CharField(default='application/json', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
