# Generated by Django 5.2.7 on 2025-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkrule',
            name='response_body',
            field=models.TextField(verbose_name='Response body'),
        ),
    ]
