# Generated by Django 5.2.7 on 2025-10-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0002_alter_networkrule_response_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkrule',
            old_name='status_code',
            new_name='response_code',
        ),
    ]
