# Generated by Django 5.2.7 on 2025-10-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_app', '0003_rename_status_code_networkrule_response_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkrule',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='networkrule',
            name='response_body',
        ),
    ]
